### ISSUE TITLE
Correction to language in "My Colleagues"

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1103]
When I click on "My colleagues", the Title of this section is: "Elizabeth Walsh's My Colleagues"
The Title should read "Elizabeth Walsh's Colleagues"

If I did not add colleagues yet, there is a statement that reads:  "This user hasn't added anyone as a colleague yet" to add a personal touch, it should read "You haven't added anyone as a colleague yet" 

![my_colleagues](https://cloud.githubusercontent.com/assets/23527358/26260147/2bebe4b2-3c9a-11e7-9d46-1a11046ecbc9.png)

**Comment by smellems** [comment]
Changing the settings of the rename_friends plugin would fix this issue and probably others where using `my colleagues` does not make sense.

I suggest we change it to `colleagues` for plural instead of `my colleagues`. This will not change the `My Colleagues` in the user menu.  It will change the header in the colleagues' page to `User's colleagues` and the first tab to `Colleagues`.  This change needs to be done by an administrator.

It would allow us to use the $usingle, $lsingle, $uplural and $lplural variables in the rename_friends language files.  I will create a pull request with related code changes.
