### ISSUE TITLE
"Secondary" search error

### ISSUE THREAD

**Issue by massierick** [gctools-outilsgc/gcconnex#1113]
There appears to be an error with the secondary search function. Here's a step-by-step to recreate the issue:

In the "Search GCConnex" box in the top menu, search for something (I searched Yukon)

On the results page, go to page 2. 

While on page 2, click in the Secondary search box (the one that only appears after a search is performed, input id="CPHContent_SearchPageControl2_q") and search for something (I tried Whitehorse). 

Doing this will give an error. 

It appears that the secondary search only works from the first page of results. Once you move forward to other pages, it causes some type of error. 

I have to wonder - what is the purpose of the secondary search? Does it have some other functionality that the main search doesn't have? If there is no difference, the easiest solution might be to get rid of it altogether. I must admit, it's a bit confusing when you have to different search boxes on the same page, with no context explaining what each should be used for.

**Comment by pandurx** [comment]
@massierick 
This issue has been resolved.

In response to your question, all queries done through "federated search" go through a Google Search Appliance that is hosted else where (we outsourced our search to a different department/branch). 

The "secondary search" is implemented as a federated search (so you can do a search throughout all of the tools; GCconnex, GCpedia, and GCintranet. When you do a search starting from GCconnex you will be forwarded to GCintranet page that will display results and options to search other tools as well, the reason that we had it done this way was simply due to the security rules enforced within our network.

**Comment by massierick** [comment]
Hi - I just tried, and the error is now occuring in a different way. 

1) I searched "yukon" in the GCintranet search. 
2) On the results page, I clicked to go to the 2nd page of results.
3) I got this error: http://search-recherche.tbs-sct.gc.ca/search?q=yukon&output=xml_no_dtd&oe=UTF-8&ie=UTF-8&lr=lang_en&start=20&num=20&site=GCConnex&getfields=*&s=3&filter=0&client=GCconnex-en_frontend

Similar error, but now occurs on the page navigation,  not on the search form submission.
