### ISSUE TITLE
Opportunities Platform > Search Opportunities > Simple Search Bar

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1432]
The simple search bar appears to be case sensitive limiting results depending on the use of capital letters. [This issue is specific to GCcollab - FYI @markwooff ]

As a regular use, I need the search to bring up results, regardless of if I use lower or upper case letters so that I can find information/people without giving up.

**Comment by mbujold** [comment]
@LemieuxGen do you have an example of what isn't working? I just tested on the live site and for instance when I search environmental I get a result where the Title is Environmental scan..

**Comment by markwooff** [comment]
I just tested this on GCcollab and was unable to re-produce the case-sensitive search results. A search for the word "masters" in lowercase still brings up a result containing "Masters" in the title:

![image](https://user-images.githubusercontent.com/5591488/30864660-47795fb6-a2a2-11e7-8223-7801ac71c900.png)

This may have been fixed with the latest code pull from GCconnex.

**Comment by mbujold** [comment]
Ok we will ignore this one for now until we get more details.

**Comment by LemieuxGen** [comment]
Received a response back from OCHRO about the issue: 
Perhaps I was mistaken and it is not a case-sensitive issue. When I search “salamis” which is the last name of one of the opportunity posters, no results appear.  However, if I search “Alton” the last name of another opportunity poster, that opportunity does show up (perhaps because his name is in the description of his post?). It might be that this issue is as simple as the system does not scan the opportunity posters’ names for simple searches.
