### ISSUE TITLE
Group Forum Titles not being properly localized

### ISSUE THREAD

**Issue by CalvinRodo** [gctools-outilsgc/gcconnex#1456]
The title for the group forums is showing the unlocalized json.
![group forum](https://user-images.githubusercontent.com/87738/30917125-3325a8c2-a369-11e7-8dbb-e7ffc945568d.png)

**Comment by KingBain** [comment]
Similar to the breadcrumbs issue
https://github.com/gctools-outilsgc/gcconnex/issues/1445#issuecomment-332320569

**Comment by KevinChagnon** [comment]
@LemieuxGen @pandurx

**Comment by KevinChagnon** [comment]
https://github.com/Phanoix/gcconnex-help/issues/21

**Comment by KevinChagnon** [comment]
@pandurx  @LemieuxGen   was this fixed pushed? it's still displaying en/fr in forum titles.

**Comment by klecuyer** [comment]
Linked to https://github.com/gctools-outilsgc/gcconnex/issues/1494

**Comment by KingBain** [comment]
Sent from my BlackBerry 10 smartphone on the Rogers network.                                                                                                                                                                                                                From: klecuyerSent: Monday, October 30, 2017 3:47 PMTo: gctools-outilsgc/gcconnexReply To: gctools-outilsgc/gcconnexCc: John Bain; CommentSubject: Re: [gctools-outilsgc/gcconnex] Group Forum Titles not being properly localized (#1456)Linked to #1494

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gctools-outilsgc/gcconnex","title":"gctools-outilsgc/gcconnex","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/gctools-outilsgc/gcconnex"}},"updates":{"snippets":[{"icon":"PERSON","message":"@klecuyer in #1456: Linked to https://github.com/gctools-outilsgc/gcconnex/issues/1494"}],"action":{"name":"View Issue","url":"https://github.com/gctools-outilsgc/gcconnex/issues/1456#issuecomment-340562689"}}}

**Comment by pandurx** [comment]
@klecuyer @LemieuxGen I thought it was pushed... but I will check

**Comment by KevinChagnon** [comment]
I have been doing some spot checks and can no longer find the JSON issue on the site.
Closing Ticket.
Re-open ticket if issue comes back.
