### ISSUE TITLE
Cannot invite members to group

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1497]
As a group owner, I cannot invite members to my group.
![image](https://user-images.githubusercontent.com/29754185/31243169-68657fc0-a9d7-11e7-9c91-7c91cc0042ae.png)

The instructions say to enter a name or username. The user I want to add is Kam.Dhanoa

If I enter the name, I enter Kam, I get a long list (only from A-F) of names that don't start with Kam, but have Kam in them. I can only see names starting with A-F so I can't scroll down to my user at K.

If I try the username, Kam.Dhanoa, I get this error message:
![image](https://user-images.githubusercontent.com/29754185/31245458-67ed9360-a9d8-11e7-83fd-daa996fefc16.png)

Because this is an auto-suggested list, could this problem be linked to https://github.com/gctools-outilsgc/gcconnex/issues/1455

If it's going to be fixed when this ticket gctools-outilsgc/gcconnex#1455 is fixed, I just need to know to inform users. Currently they can't invite group members _or_ edit group owner/operators.

**Comment by LemieuxGen** [comment]
The issue here is that from the "Invite my colleagues" to group page, the auto-suggest functionality for listing the users doesn't work the same way as the other user auto-suggest functions found on other pages, such as: @ mentions within content, add group operator, etc. 
Scenario 1: I enter the first name or the user's display name (i.e. Genevieve) - the user list is generated, but if there are many people with that same first name, I can't scroll down to see all the users and select one from the list. 
![invite to group - user list - first name - no scroll](https://user-images.githubusercontent.com/15378977/31946851-f0fa1d28-b8a0-11e7-83d5-b637a5f38949.PNG)

Scenario 2: I enter the first and last name of the user's display name - no list is generated
![invite to group - user list - first last name](https://user-images.githubusercontent.com/15378977/31946866-fb1783cc-b8a0-11e7-8bd0-619d774a9c97.PNG)

Scenario 3: I enter the user name - no list is generated
![invite to group - user list - username](https://user-images.githubusercontent.com/15378977/31946872-fe8744ca-b8a0-11e7-8003-9bd44a689c85.PNG)

**Comment by ethanWallace** [comment]
@LemieuxGen Which group were you in when creating the scenarios above?

**Comment by LemieuxGen** [comment]
@ethanWallace I believe I was in the sandbox group: https://gcconnex.gc.ca/groups/invite/3833837

**Comment by ethanWallace** [comment]
@klecuyer @LemieuxGen This feature is actually working as intended, it just has a usability issue that leads to user error. The autocomplete for this will not show users who are already members of the group. That's why the user mentioned in the main issue won't show up and why the scenarios 2 and 3 have no results.

**Comment by klecuyer** [comment]
@ethanWallace can we have this list fully populate results A-Z? Because in the initial example you still cannot add anyone past G and the name starts with K, even before he was a member of the group. There are definitely scenarios where you can't add a group member because their name is too late in the alphabet and the list populates not with names that start with those letters, but all names with that configuration in the first or last name.

**Comment by ethanWallace** [comment]
@klecuyer For performance reasons I am going to say no. Also the easy way to get around the name not showing in the given list is type more of the name in the input to provide a better filter.

**Comment by klecuyer** [comment]
@ethanWallace and if the full name is Kam and you can't add a space without losing the list? Or like Gen's example where the name is Genevieve but the last name is anything after B?

**Comment by klecuyer** [comment]
@ethanWallace oh so you can add a space to add the last name. Just retesting this now. It's just slow, my bad

**Comment by ethanWallace** [comment]
@klecuyer I'm going to take a look at possibly finding a way to speed up the autocomplete
