### ISSUE TITLE
User Option to turn off daily digest when nothing to report

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1515]
As a user, it is time-consuming and annoying to have to delete (and open) multiple emails from the Notification Digest when they all have nothing to report.

I would like the option to turn off (not receive) emails if there is nothing to report. I can see how sending no notification digest may confuse users, but an option in the notification options where I opt-in to the digest would be a simple fix, enabling users to avoid multiple emails that they have to open only to confirm that they have no notifications.

No notifications = (ideally) no emails

**Comment by klecuyer** [comment]
Linked to https://github.com/Phanoix/gcconnex-help/issues/18

**Comment by LemieuxGen** [comment]
@klecuyer because of the issues we've had in the past related to receiving/not receiving notification, we judged that receiving an saying that nothing happened in your group was the best option. It also serves as a note to users to go join more groups or add more colleagues to see more of what's happening on GCconnex. 
In addition, as we are working on a rebuild and redesign of the tools, enhancements such as this one, will not be actioned at this time. However, please tag it for rendering ideas and notifications so that we can use it for consideration. 
As a solution for the user, you can tell them that they can set up an Outlook rule to automatically delete the notification is it contains the body "Nothing to report today".
I will close this issue. Before closing the issue in the private repo, you may want to reply to the user, then close the issue (to avoid the user getting a "resolved" notification. Thanks!

**Comment by klecuyer** [comment]
@LemieuxGen Got it. Actioning now. Thanks for the context.
