### ISSUE TITLE
Filter by role in Opportunities Platform yields no results

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1702]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
As a user in the Opportunities Platform, I can see results until I filter by role (seeking/offering). If I filter by role, I see no results.

Regardless of the role I choose, it yields no results.

![image](https://user-images.githubusercontent.com/29754185/35642037-e322ed6e-068f-11e8-9067-d599db729a54.png)

![image](https://user-images.githubusercontent.com/29754185/35641966-a929c10a-068f-11e8-8e61-96e962421baf.png)
![image](https://user-images.githubusercontent.com/29754185/35642080-f42b7090-068f-11e8-9481-571ee50fddf8.png)

Even after removing the filter and refreshing the page, the results don't reappear until I click Clear Filter.

## Details on issue or enhancement
@KevinChagnon @LemieuxGen 

## For the development team
- [x] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by klecuyer** [comment]
Linked to https://github.com/Phanoix/gcconnex-help/issues/56

**Comment by LemieuxGen** [comment]
Approved. I also noticed this issue, this is high priority and should be included in the next sprint.

**Comment by ToferC** [comment]
Adding context. It seems like the issue might be related to the first row in the Opportunity Type drop-down, which is blank by default. Filtering works as long as you select one of the (non-blank) options.

**Comment by markwooff** [comment]
That _blank_ auto-selected item seems to be the issue:

![image](https://user-images.githubusercontent.com/5591488/35837274-001517c2-0ab3-11e8-9a20-ef12c8d10cc4.png)

As a user, I'd expect the 1st dropdown to use an "all opportunity types" option as default. Maybe the blank option can be changed to "all"?

**Comment by LemieuxGen** [comment]
@markwooff the reason the blank option was added because users were creating a new opportunity, they were often not taking the time to select the opportunity type, leaving the default option there as a type. This was causing issues as most opportunities were marked as being "mentoring" even if they weren't. OCHRO requested to have a blank option added so that users would have to choose an option, instead of leaving it blank. 
![gccollab_op_create op_type drop down](https://user-images.githubusercontent.com/15378977/35872286-6d6e8be2-0b34-11e8-858e-dacaab2ac08d.png)

Is there another way we can "force" users to select an opportunity type, if we don't use the blank option? We can't use "All" unfortunately.

Note, the opportunity type is supposed to be mandatory (see: https://github.com/gctools-outilsgc/gcconnex/issues/1536)

**Comment by markwooff** [comment]
@LemieuxGen it makes 100% sense to have that on the "Create Opportunity" page. It just seems like it's being carried over to the filters though which is causing the issue.

If we remove the "blank" option on the filter, then everything works fine. This change has been made on GCcollab so you can test: https://gccollab.ca/missions/main

**Comment by LemieuxGen** [comment]
Thanks great @markwooff!  
@ToferC @Troy-Lawson Would it be possible to have this pushed on GCconnex outside of the sprint? This issue is making it very difficult for users to find opportunities on the OP if they are using filters and don't know they need to go remove the selected blank option in the Opportunity type.

**Comment by ToferC** [comment]
+1

**Comment by LemieuxGen** [comment]
@smellems I see you're assigned to this ticket. As per Mark's comments, the fix is up on collab and and the code can be carried over to GCconnex. We would like to push this as soon as possible, outside of the sprint. Can you confirm once is ready to be pushed? thanks!

**Comment by markwooff** [comment]
@Phanoix maybe changes can be pulled in over the weekend?

**Comment by smellems** [comment]
This is on Prod since yesterday.  Thanks @Phanoix !
