### ISSUE TITLE
Badge for Policy Community 

### ISSUE THREAD

**Issue by hslaird** [gctools-outilsgc/gcconnex#1735]
## Need a badge for policy community's collab challenge so they can drive traffic from their government-wide innovation conference to the Tools, and host the challenge on the Tools. 
Ideally on Collab. IF not, on Connex. or both, but Collab more important if possible. 

working on getting all the info from the user Janice. Can we get badge creation in the next sprint?

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by hslaird** [comment]
@LemieuxGen tagged! thanks for info about how this is done!

**Comment by LemieuxGen** [comment]
@hslaird Do you have the information from the Policy Community for the badge?
Here's the help article we're finalizing that includes the details of what is required in order to create the avatar badge: https://support.gctools-outilsgc.ca/en/support/solutions/articles/2100032715-how-can-i-request-a-new-avatar-badge-for-my-initiative-

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
