### ISSUE TITLE
[feature] Career Marketplace: Add Opportunity Type for "Casual"

### ISSUE THREAD

**Issue by nschonni** [gctools-outilsgc/gcconnex#1814]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."

As a person working for the government as a Casual, I would like to find those seeking or promote myself as looking for Casual opportunities

## Details on issue or enhancement

So not actually a casual, but I see these get posted under deployments, Assignment, Job Sharing, and Secondments. EX: if you go to the Career Marketplace search, and enter "casual" you'll see that they are posted in many different ways.

Casual contracts are really their own thing, and should probably be treated as such.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by markwooff** [comment]
This feature actually exists on GCcollab, as well as student hires:

![image](https://user-images.githubusercontent.com/5591488/38734939-4d5c85b2-3ef5-11e8-943c-a4690f4606dc.png)

**Comment by nschonni** [comment]
Great, is the idea that the casual stuff will only go on Collab then?

**Comment by markwooff** [comment]
I believe so, perhaps you could confirm @Eldoraaoun?

**Comment by Eldoraaoun** [comment]
Thanks @markwooff  !
@nschonni Yes! Casual employment is, and will be, solely supported on GCcollab. The reason for that is because Casual opportunities should be advertised in a fair and equal method to all Canadians. If we support the mechanism on GCconnex (a site only accessible through the GoC firewall) than we would be enabling more opportunity to current Public Servants and depriving other non-government candidates from an equal chance. 

However, we recognize that this may create an unpleasant user-experience among GCconnex and GCcollab users. As a solution, our long-term vision is to have both the GCconnex and GCcollab Career Marketplace speak to one another, and create a single-sign-on facilitating efficient navigation from both platforms... Stay tuned!

**Comment by nschonni** [comment]
Makes sense :100: 
Maybe as a short term "hack", the Casual could be added to the GCConnex side, but throw a validation warning if someone tries to save it

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
