### ISSUE TITLE
GCcollab linkedin sync not working

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2032]
When syncing a profile to pull data from Linkedin, GCollab briefly displays a banner that the data was not received.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Steph4104** [comment]
Version 1 of the api is not supported since May 1, 2019.  Now, all application need to use version 2 of the API and OAuth 2.0. 
https://engineering.linkedin.com/blog/2018/12/developer-program-updates

The plugin we use is 6 years old. It's build with HybridAuth Client
https://github.com/arckinteractive/elgg_hybridauth_linkedin

**Comment by Steph4104** [comment]
I found a new version of something similar to our plugin https://github.com/arckinteractive/elgg_hybridauth/tree/master but it required elgg 2.7

**Comment by Steph4104** [comment]
Also, probably need to create new credential with a general Linkedin account (not a personnal one)

**Comment by Steph4104** [comment]
Base on the popularity of this feature and the work need to be done, I suggest to remove the plugin for now and if we update to Elgg 2.7, we can test the new version of the plugin.
