### ISSUE TITLE
GCCollab - Managed Service - Clean up old resources in Cypher

### ISSUE THREAD

**Issue by LecCory** [gctools-outilsgc/gcconnex#2533]

**Comment by Phanoix** [comment]
drg_collab_PR_common is where all the common resources for the automated / PR pipeline review instances are, 
the collab_review_<PR number> are the instance-specific resources and get cleaned up when PRs are closed

drg_collab_dev_test was a test instance for the above and I'm pretty sure the relevant IaC would have been removed by now but since bicep doesn't usually do deletion we'll need to do that manually.

**Comment by LecCory** [comment]
I have removed my own resources that were part of testing and various other PoCs. I will leave it to other resource owners to manager their own resources.

**Comment by LecCory** [comment]
Leaving maintenance of resource to the owners of said resources.
