### ISSUE TITLE
missions: error:username does not exist when sharing opportunity on Career Marketplace

### ISSUE THREAD

**Issue by Evedallas** [gctools-outilsgc/gcconnex#2606]
When  trying to share an opportunity on Career Marketplace on GCcollab, the user got this error message saying the username does not exist

We were able to reproduce the problem

![username does not exist](https://github.com/gctools-outilsgc/awesome-gctools/assets/138692330/7afc96b8-dd7f-401e-b8e9-58cbca3ff4b0)

**Comment by AdiMakkar** [comment]
The user was facing user_name issues since they were not inputting correct usernames. 
Two ways to go about looking for people's usernames to share:
1. Search people's names on the search bar. The @something represents the username for that particular user which can be later used to share. OR
2. Go to the user's profile that you'd like to share and the last string on the URL is the username of that particular user. 

Notes made to ensure some better functionality (auto fill in or drop-down) via UX is implemented when trying to share with people.
