### ISSUE TITLE
Multiple Notification

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/gcconnex#351]
GCCON-132
From: Rima 
 
 Msg: The same email below came to me 3 times, I am assuming that all users are receiving it 3 times too. The first 2 the link worked but the third one it did not. 
 
 The notification email in discussion attached.

**Comment by pandurx** [comment]
This is due to a severe performance spike, where the content that was created several times (system retrying to save) which creates several contents at once, all the same.
The link(s) do not work due to the fact that once the user realized they created one content several times, they removed the duplicates.
