### ISSUE TITLE
Separate / Filter opportunities by seeking / offering

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#614]
Split opportunities into "seeking" and "offering" sub-tabs or streams to improve the UX and simplify finding what they are looking for.  Each tab/stream would only include opportunities from that stream, but single click access to the other stream should be available. 

Offering stream would be for people creating opportunities   for other people to apply to. 

Seeking stream would be for people offering themselves up for opportunities. 

May require some re-jigging of opportunity types so that each one has a offering / seeking component or separate out opportunity types into two elements in Create Opportunities:
1) offering, seeking
2) type of opportunity (secondment, deployment, micro-mission, mentoring, job shadowing, etc.)

The two element method would reduce the length of drop down lists and is therefore preferable.

**Comment by ycharron** [comment]
A few questions:
* When creating (or editing) an opportunity I added:
Opportunity role:	(required)
(radio) Create an opportunity for others (offering)
(radio) Offer myself for an opportunity (seeking)
I also added a new "Opportunity Role" filter with two options: Offering, Seeking.  Are you ok with these names?
* There are now four filters listed.  The "Sort Opportunities by" and "In the following order" should be merged as that's how it's typically done.  I recommend we merge them but should probably be done as part of another issue.
* What do you think of always having the "Filter and Sort" bar always displayed instead of hidden behind a button?  I don't see any reason why it should be hidden and it would make it quicker to "Filter and Sort" the opportunities.
* I also recommend turning "Type of opportunity" into radio buttons with in-context help.  Probably as part of another issue.

Everything seems to be working fine.  Need some more testing and polishing.

**Comment by ycharron** [comment]
What do you think of "wanted" instead of "seeking"?

**Comment by ToferC** [comment]
Good suggestions, Yves. I like unhiding the filter/sort. 

Suggest we stick with offering/seeking. The language is more specific. 

I also like the radio opportunity type idea as a separate issue. Looking forward to testing this!

Thanks so much.

**Comment by ycharron** [comment]
Please have a look at the images below and let me know if you'd like to modify any of the wording, elements, etc.  I would also need French translations once you've accepted the English wording:

![screenshot-create-opportunity](https://cloud.githubusercontent.com/assets/4921983/23727620/cac85428-0426-11e7-875d-4222a06f0700.png)
![screenshot-filter_mission-cards](https://cloud.githubusercontent.com/assets/4921983/23727621/cacc231e-0426-11e7-8ab2-fe751079ad82.png)

**Comment by ycharron** [comment]
Note that only new (or edited) entries will have the "offering/seeking" option set.  All archived/current opportunities will not have that specified.
