### ISSUE TITLE
Breadcrumbs and navigation from sub-group to main group

### ISSUE THREAD

**Issue by PhilAndrecheck** [gctools-outilsgc/gcconnex#646]
The breadcrumbs do not allow a user to navigate back to the main group from a sub-group when you're in a "page" view (not the view of all the groupview ... the "pages" previous breadcrumb takes you back to "all site pages".
Consider having it take you to main group.
![navigation](https://cloud.githubusercontent.com/assets/22220521/21643757/1c8687d6-d258-11e6-83f4-c5c506903681.PNG)

**Comment by ialexca** [comment]
Once you clicked on the main group breadcrumb item, in french, the group name is displayed in english.

**Comment by pabrams** [comment]
Not sure if I'm reproducing the same issue or not...
1. Create ParentGroup
2. in group, create subgroup1
3. Visit subgroup.. Breadcrumb is now Home -> Groups -> ParentGroup -> Subgroup1
3. in subgroup, creat blogpost
4. click  on blog post
5. breadcrumb is now Home -> Blogs -> Subgroup1 -> blogpost
breadcrumb at bullet 5 seems wrong to me...
should be ParentGroup instead of Blogs?
but maybe this is by design?

**Comment by pabrams** [comment]
Team 4 is doing some analysis on this issue for hackathon.  No promises that we can fix it though.

**Comment by ialexca** [comment]
Tomorrow, we Will see if elgg v2 will fix this issue.

**Comment by pabrams** [comment]
I'm curious to see if Elgg v2 makes any improvements to the navigation system, but this currently feels like it's behaving as designed.  In @PhilAndrecheck's screenshot, I guess he's just moved away from a the GC 2.0 Tools subgroup's "Profile" page by visiting a "Page" listed in that subgroup, and in doing so he's the breadcrumb hierarchy has changed from "Group" to "Page", and so he's lost the reference to the subgroup's parent in the breadcrumbs. To get back, he'd need to click that subgroup link in the breadcrumb, which would take him to the GC 2.0 Tools Pages (listing all the Pages in that subGroup), and from there he'd have to click "About" to get to the subgroup's Profile page, which contains the breadcrumbs he's after (parent group, and its parents as well, if there are any).  It would be easy enough to change the link behind the "GC 2.0 Tools Team" in the screenshot to go directly to the subgroup's Profile view instead of to it's "Pages" view, but I think that would break the existing design.  Another idea is to insert extra breadcrumbs in the views, for example perhaps insert links to the entire group hierarchy, including the subgroup's Profile page, after the "Pages" breadcrumb?

**Comment by pabrams** [comment]
In our opinion, this is working as designed and the issue as currently worded should be closed.  The breadcrumbs aren't intended to keep a history of where the user has been, but rather where the user currently is in the site.  To get back to the parent group, OP could hit browser back button a couple of times.  
It may be appropriate to open one or more separate issues, if not already open:
- Upgrade gcconnex to latest version of Elgg
- If the breadcrumb/navigation usability could be improved, a more general issue could be opened.
- Another idea might be to improve the AU_SUBGROUP module to handle breadcrumbs on any resource owned by that subgroup, and insert the subgroup's group hierarchy into the breadcrumbs on those resource pages.  However, while this may satisfy some users such as @PhilAndrecheck , it might be confusing for other users.

**Comment by Troy-Lawson** [comment]
not likely to fix prior to rebuild
