### ISSUE TITLE
gcconnex: I want to be able to export or sync my GCconnex calendar into my Outlook calendar

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#717]
Enhancement of existing feature
As a Regular User, I need I want to be able to export or sync my GCconnex calendar into my Outlook calendar because In order to organize multiple people across schedules we need an effective way to see when people have appointments outside of GCconnex as well as within. Being able to mass add or sync My GCconnex Calendar to my Outlook Calendar(or any calendar program ideally) would help address this issue. Some people are not on GCconnex and as the number of events starts to grow it is increasingly difficult to add everything manually.

marc.sukstorf@tbs-sct.gc.ca - 1/19/2017 15:20:25

**Comment by ToferC** [comment]
This is a common and valuable request, but very difficult to implement as departments set their own outlook permissions and most block calendar invitations for security reasons.  Would be great to see if we can get GCTools whitelisted, but otherwise we won't be able to make this happen.  @cdegrass - could you please assess and assign or close issue? Thanks! @KevinChagnon

**Comment by Troy-Lawson** [comment]
closing as will not be tackled in current version of the tools. will look into for the rebuild
