### ISSUE TITLE
Search results showing "Language Selection" instead of title

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#772]
The search results are now showing "Language Selection" instead of the content title. This seems to be the case for the content where the language is split using the new "split languages feature". See screen shot. 
![sgsa - language selection](https://cloud.githubusercontent.com/assets/15378977/22602201/3cd4ce92-ea10-11e6-9510-cbe3401090af.JPG)

**Comment by LemieuxGen** [comment]
@pandurx Were there changes applied last night that would have caused this? I know you were working on a fix for the titles to appear in both languages... Thanks!

**Comment by KevinChagnon** [comment]
+1

**Comment by pandurx** [comment]
The changes that i did for the titles did not make it to production

**Comment by pandurx** [comment]
https://github.com/gctools-outilsgc/gcconnex/pull/805

**Comment by LemieuxGen** [comment]
@pandurx I tested the search this morning and we still had results with "Language Selection" replacing the content title, and also your email address. See screen shots.
![gsa_language selection_feb22](https://cloud.githubusercontent.com/assets/15378977/23213527/4301f0ec-f8d9-11e6-8b7b-e7a678657d99.JPG)

**Comment by cdegrass** [comment]
I'm not sure if the GSA code was pushed to production and even if it was the GSA will need to reindex and this will only be done after all the patches are in place.  ent from my BlackBerry 10 smartphone on the Rogers network.                                                                                                                                                                                                                From: LemieuxGenSent: Wednesday, February 22, 2017 8:31 AMTo: gctools-outilsgc/gcconnexReply To: gctools-outilsgc/gcconnexCc: SubscribedSubject: Re: [gctools-outilsgc/gcconnex] Search results showing "Language Selection" instead of title (#772)@pandurx I tested the search this morning and we still had results with "Language Selection" replacing the content title, and also your email address. See screen shots.


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gctools-outilsgc/gcconnex","title":"gctools-outilsgc/gcconnex","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/gctools-outilsgc/gcconnex"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LemieuxGen in #772: @pandurx I tested the search this morning and we still had results with \"Language Selection\" replacing the content title, and also your email address. See screen shots.\r\n![gsa_language selection_feb22](https://cloud.githubusercontent.com/assets/15378977/23213527/4301f0ec-f8d9-11e6-8b7b-e7a678657d99.JPG)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/gctools-outilsgc/gcconnex/issues/772#issuecomment-281669533"}}}

**Comment by sboots** [comment]
+1 on this one - thanks for looking into it!

![gcconnex-error-language-selection](https://cloud.githubusercontent.com/assets/263472/23309405/9439c0ee-fa7c-11e6-983d-4fb8a1d28a98.PNG)

**Comment by LemieuxGen** [comment]
This is an issue, still. Some results now showing "Site navigation menu".
![search_title site navigation menu](https://user-images.githubusercontent.com/15378977/29283439-b209b79c-80f4-11e7-99a1-0d787b491bd0.JPG)
