### ISSUE TITLE
"My Profile" sections broken

### ISSUE THREAD

**Issue by gabrielcossette-ca** [gctools-outilsgc/gcconnex#853]
To reproduce:
1. Click on your name (top left) and **My Profile** button
2. Click on any of the following sections: Portfolio, Files, Blog, Wire posts, Badge Progress...
3. Nothing happens

Is this a wide issue or isolated to my profile? Weirdly, only the "Widgets" section works ;)

Thanks!

**Comment by ToferC** [comment]
Thanks for sharing Gabriel. This doesn't seem to be site-wide. What browser and version are you using. Is this desktop or mobile?

**Comment by gabrielcossette-ca** [comment]
You are right, it seems isolated to my profile. I tried to view another public profile and it worked.

Can you try to view my profile to see if it works on your side please? https://gcconnex.gc.ca/profile/gabrielcossette

And then select **Blog** for example, thanks!

**Comment by ToferC** [comment]
@gabrielcossette-ca - confirmed.  The items are showing, but they are all down below your widgets.  It seems like there is a missing </div> in there somewhere.  Do you have an iframe in your widgets?  Can you try removing your widgets and see if things revert back to normal?

Otherwise confirming this as an issue.

**Comment by gabrielcossette** [comment]
Hi!

Weird, I looked again this morning and the problem is now gone! You can close the issue.

Thanks Chris for the help!
