### ISSUE TITLE
Exception #1491324287. when replying to a discussion

### ISSUE THREAD

**Issue by rleir** [gctools-outilsgc/gcconnex#904]
Hi all
I replied to a discussion (link below) and got an exception. After a few reloads I gave up. You will see that my reply actually got posted several times.
Look at https://gcconnex.gc.ca/discussion/view/24935422/team-project-ideas-list-them-here
A few searches did not turn up exception 1491324287. Would someone like to look in the logs for Apr4 at 12:45 or thereabouts and tell me what the error was?

And to be specific, the issue would be that the reply should not get saved if there is an exception.
Thanks
Rick

**Comment by rleir** [comment]
Hmm, I cannot reply again. This time it is Exception #1491329701. As before, my reply did actually get posted.  2:20 pm Apr4. 

And to be specific, the issue would be: if there is a reason that I cannot reply, then the feedback could be worded so as to help me solve the problem.
Thanks -- Rick

**Comment by rleir** [comment]
This occurs on gccollab too. I just got Exception #1491409832. Apr5 12:32

**Comment by ToferC** [comment]
Can someone pls. look into this? Thanks, Rick.

**Comment by KevinChagnon** [comment]
Another user reporting getting Exception # 190886420 when trying to Create a Discussion in group: https://gcconnex.gc.ca/groups/profile/5317640/heads-of-learning-forum-holf

User is: Martine.Gauthier

![holf oops](https://cloud.githubusercontent.com/assets/23527358/24768370/5068d93a-1ad0-11e7-90ca-ffc5a08b671a.jpg)

I joined the group myself, attempted to Create New Discussion; the system hung for quite some time and then posted 2 messages confirming the same posted was successfully posted.  It actually posted 3 times:

![heads of learning discussion](https://cloud.githubusercontent.com/assets/23527358/24768450/90f70bac-1ad0-11e7-9174-4a6af3ba2540.JPG)

I have since deleted the posts and left the group.

**Comment by rleir** [comment]
Hi Chris and Kevin, This should have jumped out at me: the exception number is just a timestamp, to help with looking in the logs. cheers -- Rick
